# Generated by Django 5.0.7 on 2024-09-24 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommodityInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commodityTime', models.DateField(auto_now_add=True, verbose_name='发布时间')),
                ('commodityType', models.SmallIntegerField(choices=[(0, '全部'), (1, '个人')], default=0, verbose_name='商品类型')),
                ('commodityName', models.CharField(max_length=11, verbose_name='商品名称')),
                ('commodityPhoto', models.CharField(max_length=200, verbose_name='店铺照片')),
                ('commodityShopName', models.CharField(max_length=50, verbose_name='店铺名称')),
                ('commodityShopNumber', models.IntegerField(verbose_name='商品库存量')),
                ('commodityOther', models.CharField(max_length=11, verbose_name='商品备注')),
                ('commodityPriceBefore', models.IntegerField(verbose_name='优惠前价格')),
                ('commodityPriceAfter', models.IntegerField(verbose_name='优惠后价格')),
                ('commodityIntroduce', models.CharField(blank=True, max_length=1000, null=True, verbose_name='商品介绍')),
                ('businessId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='商家id', to='app01.businessinformation')),
            ],
        ),
    ]
