# Generated by Django 5.0.7 on 2024-09-24 14:19

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_commodityinformation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commodityinformation',
            name='commodityPriceAfter',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='优惠后价格'),
        ),
        migrations.AlterField(
            model_name='commodityinformation',
            name='commodityPriceBefore',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='优惠前价格'),
        ),
        migrations.AlterField(
            model_name='commodityinformation',
            name='commodityShopNumber',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='商品库存量'),
        ),
    ]
