# Generated by Django 5.0.7 on 2024-10-09 02:34

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_alter_commodityinformation_commoditypriceafter_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdersInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=20, verbose_name='订单id')),
                ('order_time', models.DateField(auto_now_add=True, verbose_name='下单时间')),
                ('order_commodity_name', models.CharField(max_length=11, verbose_name='商品名称')),
                ('order_shop_name', models.CharField(max_length=50, verbose_name='店铺名称')),
                ('order_commodity_photo', models.CharField(max_length=200, verbose_name='商品照片')),
                ('order_commodity_type', models.SmallIntegerField(choices=[(0, '竹编家具'), (1, '工艺品')], default=0, verbose_name='商品类型')),
                ('order_people_account', models.CharField(max_length=11, unique=True, verbose_name='下单账号')),
                ('order_people_phone', models.CharField(max_length=11, unique=True, verbose_name='下单手机号')),
                ('order_people_name', models.CharField(blank=True, max_length=11, null=True, verbose_name='下单人姓名')),
                ('order_people_address', models.CharField(blank=True, max_length=20, null=True, verbose_name='收货地址')),
                ('order_people_detailed_address', models.CharField(blank=True, max_length=100, null=True, verbose_name='详细收货地址')),
                ('order_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='下单数量')),
                ('order_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='下单价格')),
                ('commodityName', models.CharField(max_length=11, verbose_name='商品名称')),
                ('commodityPhoto', models.CharField(max_length=200, verbose_name='店铺照片')),
                ('commodityShopName', models.CharField(max_length=50, verbose_name='店铺名称')),
                ('commodityShopNumber', models.IntegerField(validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='商品库存量')),
                ('commodityOther', models.CharField(max_length=11, verbose_name='商品备注')),
                ('commodityPriceBefore', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='优惠前价格')),
                ('commodityPriceAfter', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='优惠后价格')),
                ('commodityIntroduce', models.CharField(blank=True, max_length=1000, null=True, verbose_name='商品介绍')),
            ],
        ),
        migrations.AlterField(
            model_name='logininformation',
            name='username',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='姓名'),
        ),
    ]
