# Generated by Django 5.0.7 on 2024-10-10 04:13

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_remove_ordersinformation_commodityintroduce_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordersinformation',
            name='order_people_account',
            field=models.CharField(max_length=11, verbose_name='下单账号'),
        ),
        migrations.AlterField(
            model_name='ordersinformation',
            name='order_people_detailed_address',
            field=models.CharField(blank=True, max_length=65, null=True, verbose_name='详细收货地址'),
        ),
        migrations.AlterField(
            model_name='ordersinformation',
            name='order_people_phone',
            field=models.CharField(max_length=11, verbose_name='下单手机号'),
        ),
        migrations.AlterField(
            model_name='ordersinformation',
            name='order_price',
            field=models.DecimalField(decimal_places=2, max_digits=30, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='下单价格'),
        ),
    ]
